use super::types::{SyncErrorOrigin as Origin, SyncErrorStage as Stage};

pub(super) const CONTEXTS: &[(&str, Origin, Stage)] = &[
    ("AMBIGUOUS_IDENTITY", Origin::DesktopCds, Stage::Startup),
    (
        "ATTACHMENT_PATH_INVALID",
        Origin::DesktopPlugin,
        Stage::Messages,
    ),
    ("BATTERY_TOO_LOW", Origin::MobileNative, Stage::Preflight),
    ("CANCELLED", Origin::DesktopCds, Stage::Shutdown),
    ("CDS_ERROR", Origin::DesktopCds, Stage::Startup),
    ("CDS_PROTOCOL_MISMATCH", Origin::DesktopCds, Stage::Startup),
    ("CDS_UNAVAILABLE", Origin::DesktopCds, Stage::Startup),
    ("FINAL_ACK_TIMEOUT", Origin::MobileSync, Stage::Finalize),
    ("HEALTH_CHECK_FAILED", Origin::DesktopCds, Stage::Startup),
    (
        "HISTORY_SOURCE_INVALID",
        Origin::DesktopPlugin,
        Stage::Messages,
    ),
    ("HTTP_ERROR", Origin::DesktopCds, Stage::Startup),
    ("INTERNAL_ERROR", Origin::DesktopCds, Stage::Startup),
    ("INVALID_CONFIGURATION", Origin::DesktopCds, Stage::Startup),
    ("INVALID_REQUEST", Origin::DesktopCds, Stage::Startup),
    ("INVALID_RESPONSE", Origin::DesktopCds, Stage::Startup),
    (
        "MANIFEST_RESPONSE_TIMEOUT",
        Origin::MobileSync,
        Stage::OwnerMetadata,
    ),
    ("MESSAGE_DIFF_FAILED", Origin::DesktopCds, Stage::Messages),
    (
        "MESSAGE_MANIFEST_FAILED",
        Origin::DesktopCds,
        Stage::Messages,
    ),
    (
        "MOBILE_ATTACHMENT_INVALID",
        Origin::DesktopPlugin,
        Stage::Messages,
    ),
    ("MOBILE_SYNC_ERROR", Origin::MobileSync, Stage::Shutdown),
    ("NOT_FOUND", Origin::DesktopCds, Stage::Startup),
    (
        "PHASE3_RESPONSE_TIMEOUT",
        Origin::MobileSync,
        Stage::Messages,
    ),
    (
        "PLUGIN_VERSION_MISMATCH",
        Origin::DesktopPlugin,
        Stage::Handshake,
    ),
    ("POWER_SAVE_MODE", Origin::MobileNative, Stage::Preflight),
    (
        "PROTOCOL_DUPLICATE_KEY",
        Origin::MobileSync,
        Stage::Handshake,
    ),
    ("PROTOCOL_INVALID", Origin::MobileSync, Stage::Handshake),
    ("PROTOCOL_MISMATCH", Origin::DesktopPlugin, Stage::Handshake),
    ("RESPONSE_TOO_LARGE", Origin::MobileSync, Stage::Messages),
    ("SEARCH_UNAVAILABLE", Origin::DesktopCds, Stage::Startup),
    ("SERVICE_BUSY", Origin::DesktopCds, Stage::Startup),
    (
        "SYNC_ATTACHMENT_NOT_FOUND",
        Origin::DesktopPlugin,
        Stage::Messages,
    ),
    (
        "SYNC_ATTACHMENT_READ_FAILED",
        Origin::DesktopPlugin,
        Stage::Messages,
    ),
    (
        "SYNC_ATTACHMENT_WRITE_FAILED",
        Origin::DesktopPlugin,
        Stage::Messages,
    ),
    ("SYNC_ATTEMPT_FAILED", Origin::MobileSync, Stage::Startup),
    ("SYNC_AUTH_FAILED", Origin::MobileSync, Stage::Connect),
    (
        "SYNC_AVATAR_NOT_FOUND",
        Origin::DesktopPlugin,
        Stage::OwnerMetadata,
    ),
    (
        "SYNC_AVATAR_READ_FAILED",
        Origin::MobileSync,
        Stage::OwnerMetadata,
    ),
    (
        "SYNC_AVATAR_WRITE_FAILED",
        Origin::MobileSync,
        Stage::OwnerMetadata,
    ),
    ("SYNC_BUDGET_EXCEEDED", Origin::MobileSync, Stage::Messages),
    (
        "SYNC_CHANGE_FEED_FAILED",
        Origin::MobileSync,
        Stage::History,
    ),
    (
        "SYNC_CHANGE_FEED_UNAVAILABLE",
        Origin::DesktopPlugin,
        Stage::History,
    ),
    ("SYNC_DB_DRAIN_FAILED", Origin::MobileSync, Stage::Finalize),
    (
        "SYNC_DB_QUERY_FAILED",
        Origin::MobileSync,
        Stage::TopicValidation,
    ),
    ("SYNC_DB_UNAVAILABLE", Origin::MobileSync, Stage::Startup),
    ("SYNC_DELETE_FAILED", Origin::MobileSync, Stage::Messages),
    ("SYNC_DELETE_INVALID", Origin::MobileSync, Stage::Messages),
    (
        "SYNC_ENTITY_BATCH_FAILED",
        Origin::MobileSync,
        Stage::TopicMetadata,
    ),
    (
        "SYNC_ENTITY_NOT_FOUND",
        Origin::DesktopPlugin,
        Stage::OwnerMetadata,
    ),
    (
        "SYNC_ENTITY_READ_FAILED",
        Origin::MobileSync,
        Stage::OwnerMetadata,
    ),
    (
        "SYNC_ENTITY_WRITE_FAILED",
        Origin::MobileSync,
        Stage::OwnerMetadata,
    ),
    (
        "SYNC_INDEX_INVALID",
        Origin::MobileSync,
        Stage::TopicValidation,
    ),
    (
        "SYNC_MESSAGE_READ_FAILED",
        Origin::MobileSync,
        Stage::Messages,
    ),
    (
        "SYNC_MESSAGE_WRITE_FAILED",
        Origin::MobileSync,
        Stage::Messages,
    ),
    (
        "SYNC_OWNER_CONFLICT",
        Origin::DesktopPlugin,
        Stage::TopicMetadata,
    ),
    (
        "SYNC_PHASE_STALLED",
        Origin::MobileSync,
        Stage::TopicMetadata,
    ),
    (
        "SYNC_PREVIOUS_SESSION_EXIT_FAILED",
        Origin::MobileSync,
        Stage::Shutdown,
    ),
    (
        "SYNC_PROTOCOL_INVALID",
        Origin::MobileSync,
        Stage::OwnerMetadata,
    ),
    ("SYNC_REQUEST_INVALID", Origin::MobileSync, Stage::Connect),
    (
        "SYNC_SNAPSHOT_STALE",
        Origin::DesktopPlugin,
        Stage::Messages,
    ),
    ("SYNC_STREAM_FAILED", Origin::MobileSync, Stage::Messages),
    (
        "SYNC_VERSION_INCOMPATIBLE",
        Origin::DesktopPlugin,
        Stage::Handshake,
    ),
    ("TIMEOUT", Origin::DesktopCds, Stage::Startup),
    ("TOPIC_HASH_FAILED", Origin::MobileSync, Stage::Messages),
    (
        "TOPIC_HASH_RESPONSE_TIMEOUT",
        Origin::MobileSync,
        Stage::TopicValidation,
    ),
    ("TOPIC_NOT_FOUND", Origin::DesktopPlugin, Stage::Messages),
    ("UNAUTHORIZED", Origin::DesktopCds, Stage::Connect),
    ("UNAVAILABLE", Origin::DesktopCds, Stage::Startup),
    ("VERSION_ACK_INVALID", Origin::MobileSync, Stage::Handshake),
    (
        "VERSION_CHECK_DUPLICATE",
        Origin::MobileSync,
        Stage::Handshake,
    ),
    (
        "VERSION_CHECK_INVALID",
        Origin::MobileSync,
        Stage::Handshake,
    ),
    (
        "VERSION_CHECK_REQUIRED",
        Origin::MobileSync,
        Stage::Handshake,
    ),
    (
        "VERSION_CHECK_TIMEOUT",
        Origin::MobileSync,
        Stage::Handshake,
    ),
];
