use super::types::{SyncErrorCategory as Category, SyncRetryAction as Retry};

pub(super) const SEMANTICS: &[(&str, Category, Retry)] = &[
    ("AMBIGUOUS_IDENTITY", Category::Data, Retry::Manual),
    (
        "ATTACHMENT_PATH_INVALID",
        Category::Storage,
        Retry::AfterUserAction,
    ),
    ("BATTERY_TOO_LOW", Category::Device, Retry::AfterUserAction),
    ("CANCELLED", Category::Internal, Retry::Never),
    ("CDS_ERROR", Category::Internal, Retry::Manual),
    (
        "CDS_PROTOCOL_MISMATCH",
        Category::Compatibility,
        Retry::AfterUserAction,
    ),
    ("CDS_UNAVAILABLE", Category::Internal, Retry::Manual),
    ("FINAL_ACK_TIMEOUT", Category::Connection, Retry::Manual),
    ("HEALTH_CHECK_FAILED", Category::Connection, Retry::Manual),
    (
        "HISTORY_SOURCE_INVALID",
        Category::Data,
        Retry::AfterUserAction,
    ),
    ("HTTP_ERROR", Category::Connection, Retry::Manual),
    ("INTERNAL_ERROR", Category::Internal, Retry::Manual),
    (
        "INVALID_CONFIGURATION",
        Category::Configuration,
        Retry::AfterUserAction,
    ),
    (
        "INVALID_REQUEST",
        Category::Protocol,
        Retry::AfterUserAction,
    ),
    (
        "INVALID_RESPONSE",
        Category::Protocol,
        Retry::AfterUserAction,
    ),
    (
        "MANIFEST_RESPONSE_TIMEOUT",
        Category::Connection,
        Retry::Manual,
    ),
    ("MESSAGE_DIFF_FAILED", Category::Storage, Retry::Manual),
    ("MESSAGE_MANIFEST_FAILED", Category::Storage, Retry::Manual),
    (
        "MOBILE_ATTACHMENT_INVALID",
        Category::Data,
        Retry::AfterUserAction,
    ),
    ("MOBILE_SYNC_ERROR", Category::Internal, Retry::Manual),
    ("NOT_FOUND", Category::Data, Retry::Manual),
    (
        "PHASE3_RESPONSE_TIMEOUT",
        Category::Connection,
        Retry::Manual,
    ),
    (
        "PLUGIN_VERSION_MISMATCH",
        Category::Compatibility,
        Retry::AfterUserAction,
    ),
    ("POWER_SAVE_MODE", Category::Device, Retry::AfterUserAction),
    (
        "PROTOCOL_DUPLICATE_KEY",
        Category::Protocol,
        Retry::AfterUserAction,
    ),
    (
        "PROTOCOL_INVALID",
        Category::Protocol,
        Retry::AfterUserAction,
    ),
    (
        "PROTOCOL_MISMATCH",
        Category::Compatibility,
        Retry::AfterUserAction,
    ),
    ("RESPONSE_TOO_LARGE", Category::Data, Retry::AfterUserAction),
    ("SEARCH_UNAVAILABLE", Category::Storage, Retry::Manual),
    ("SERVICE_BUSY", Category::Connection, Retry::Manual),
    ("SYNC_ATTACHMENT_NOT_FOUND", Category::Data, Retry::Manual),
    (
        "SYNC_ATTACHMENT_READ_FAILED",
        Category::Storage,
        Retry::Manual,
    ),
    (
        "SYNC_ATTACHMENT_WRITE_FAILED",
        Category::Storage,
        Retry::Manual,
    ),
    ("SYNC_ATTEMPT_FAILED", Category::Internal, Retry::Manual),
    (
        "SYNC_AUTH_FAILED",
        Category::Configuration,
        Retry::AfterUserAction,
    ),
    ("SYNC_AVATAR_NOT_FOUND", Category::Data, Retry::Manual),
    ("SYNC_AVATAR_READ_FAILED", Category::Storage, Retry::Manual),
    ("SYNC_AVATAR_WRITE_FAILED", Category::Storage, Retry::Manual),
    (
        "SYNC_BUDGET_EXCEEDED",
        Category::Data,
        Retry::AfterUserAction,
    ),
    ("SYNC_CHANGE_FEED_FAILED", Category::Storage, Retry::Manual),
    (
        "SYNC_CHANGE_FEED_UNAVAILABLE",
        Category::Configuration,
        Retry::AfterUserAction,
    ),
    ("SYNC_DB_DRAIN_FAILED", Category::Storage, Retry::Manual),
    ("SYNC_DB_QUERY_FAILED", Category::Storage, Retry::Manual),
    ("SYNC_DB_UNAVAILABLE", Category::Storage, Retry::Manual),
    ("SYNC_DELETE_FAILED", Category::Storage, Retry::Manual),
    (
        "SYNC_DELETE_INVALID",
        Category::Protocol,
        Retry::AfterUserAction,
    ),
    ("SYNC_ENTITY_BATCH_FAILED", Category::Storage, Retry::Manual),
    ("SYNC_ENTITY_NOT_FOUND", Category::Data, Retry::Manual),
    ("SYNC_ENTITY_READ_FAILED", Category::Storage, Retry::Manual),
    ("SYNC_ENTITY_WRITE_FAILED", Category::Storage, Retry::Manual),
    ("SYNC_INDEX_INVALID", Category::Storage, Retry::Manual),
    ("SYNC_MESSAGE_READ_FAILED", Category::Storage, Retry::Manual),
    (
        "SYNC_MESSAGE_WRITE_FAILED",
        Category::Storage,
        Retry::Manual,
    ),
    ("SYNC_OWNER_CONFLICT", Category::Data, Retry::Manual),
    ("SYNC_PHASE_STALLED", Category::Internal, Retry::Manual),
    (
        "SYNC_PREVIOUS_SESSION_EXIT_FAILED",
        Category::Internal,
        Retry::Manual,
    ),
    (
        "SYNC_PROTOCOL_INVALID",
        Category::Protocol,
        Retry::AfterUserAction,
    ),
    (
        "SYNC_REQUEST_INVALID",
        Category::Protocol,
        Retry::AfterUserAction,
    ),
    ("SYNC_STREAM_FAILED", Category::Connection, Retry::Manual),
    (
        "SYNC_VERSION_INCOMPATIBLE",
        Category::Compatibility,
        Retry::AfterUserAction,
    ),
    ("TIMEOUT", Category::Connection, Retry::Manual),
    ("TOPIC_HASH_FAILED", Category::Storage, Retry::Manual),
    (
        "TOPIC_HASH_RESPONSE_TIMEOUT",
        Category::Connection,
        Retry::Manual,
    ),
    ("TOPIC_NOT_FOUND", Category::Data, Retry::Manual),
    (
        "UNAUTHORIZED",
        Category::Configuration,
        Retry::AfterUserAction,
    ),
    ("UNAVAILABLE", Category::Connection, Retry::Manual),
    (
        "VERSION_ACK_INVALID",
        Category::Protocol,
        Retry::AfterUserAction,
    ),
    (
        "VERSION_CHECK_DUPLICATE",
        Category::Protocol,
        Retry::AfterUserAction,
    ),
    (
        "VERSION_CHECK_INVALID",
        Category::Protocol,
        Retry::AfterUserAction,
    ),
    (
        "VERSION_CHECK_REQUIRED",
        Category::Protocol,
        Retry::AfterUserAction,
    ),
    ("VERSION_CHECK_TIMEOUT", Category::Connection, Retry::Manual),
];
