#!/usr/bin/env python3
"""验证 vcp-mobile 插件的 Tauri ACL 默认权限集可被正确展开。"""

from __future__ import annotations

import json
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PLUGIN_PERMISSIONS = ROOT / "src-tauri/plugins/vcp-mobile/permissions"
DEFAULT_CAPABILITY = ROOT / "src-tauri/capabilities/default.json"
NOTIFICATION_CAPABILITY = ROOT / "src-tauri/capabilities/agent-notifications.json"
SENSITIVE_COMMANDS = {"run_root_command", "show_system_notification"}


def load_toml(path: Path) -> dict:
    with path.open("rb") as file:
        return tomllib.load(file)


def fail(message: str) -> None:
    raise SystemExit(f"vcp-mobile ACL 校验失败: {message}")


default_file = load_toml(PLUGIN_PERMISSIONS / "default.toml")
default_set = default_file.get("default")
if not isinstance(default_set, dict):
    fail("default.toml 必须使用 Tauri 保留的 [default] 权限集")

inline_permissions = default_file.get("permission", [])
if any(permission.get("identifier") == "default" for permission in inline_permissions):
    fail('不能用 [[permission]] identifier = "default" 代替 [default]')

permission_map: dict[str, dict] = {}
for path in sorted((PLUGIN_PERMISSIONS / "autogenerated/commands").glob("*.toml")):
    for permission in load_toml(path).get("permission", []):
        permission_map[permission["identifier"]] = permission

default_permissions = default_set.get("permissions", [])
if not isinstance(default_permissions, list) or not default_permissions:
    fail("[default].permissions 不能为空")

missing_permissions = sorted(set(default_permissions) - permission_map.keys())
if missing_permissions:
    fail(f"引用了不存在的权限: {', '.join(missing_permissions)}")

resolved_commands = {
    command
    for identifier in default_permissions
    for command in permission_map[identifier].get("commands", {}).get("allow", [])
}
if "check_all_permissions" not in resolved_commands:
    fail("默认权限集未授权启动所需的 check_all_permissions")

leaked_default_commands = sorted(resolved_commands & SENSITIVE_COMMANDS)
if leaked_default_commands:
    fail(f"默认权限集包含敏感命令: {', '.join(leaked_default_commands)}")

all_file = load_toml(PLUGIN_PERMISSIONS / "all.toml")
allow_all = next(
    (
        permission
        for permission in all_file.get("permission", [])
        if permission.get("identifier") == "allow-all"
    ),
    None,
)
if allow_all is None:
    fail("all.toml 缺少 allow-all 权限")

allow_all_commands = set(allow_all.get("commands", {}).get("allow", []))
leaked_all_commands = sorted(allow_all_commands & SENSITIVE_COMMANDS)
if leaked_all_commands:
    fail(f"allow-all 包含敏感命令: {', '.join(leaked_all_commands)}")

default_capability = json.loads(DEFAULT_CAPABILITY.read_text(encoding="utf-8"))
if "vcp-mobile:default" not in default_capability.get("permissions", []):
    fail("主窗口 capability 未启用 vcp-mobile:default")

notification_capability = json.loads(
    NOTIFICATION_CAPABILITY.read_text(encoding="utf-8")
)
if "vcp-mobile:allow-show-system-notification" not in notification_capability.get(
    "permissions", []
):
    fail("系统通知命令未通过独立 capability 授权")

print(
    f"vcp-mobile ACL 校验通过: 默认权限解析到 {len(resolved_commands)} 条命令，敏感命令保持隔离"
)
