#!/usr/bin/env python3
"""验证 vcp-mobile 插件 ACL；仅依赖 Python 3.10 标准库。"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import TypedDict


ROOT = Path(__file__).resolve().parents[1]
PLUGIN_PERMISSIONS = ROOT / "src-tauri/plugins/vcp-mobile/permissions"
DEFAULT_CAPABILITY = ROOT / "src-tauri/capabilities/default.json"
NOTIFICATION_CAPABILITY = ROOT / "src-tauri/capabilities/agent-notifications.json"
SENSITIVE_COMMANDS = {"run_root_command", "show_system_notification"}
ACL_TOKEN_PATTERN = re.compile(r'"([a-z0-9_-]+)"')


class InlinePermission(TypedDict):
    identifier: str
    commands: list[str]


def fail(message: str) -> None:
    raise SystemExit(f"vcp-mobile ACL 校验失败: {message}")


def read_acl(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def extract_string(block: str, key: str) -> str:
    match = re.search(
        rf'^\s*{re.escape(key)}\s*=\s*"([a-z0-9_-]+)"\s*$',
        block,
        flags=re.MULTILINE,
    )
    if match is None:
        fail(f"ACL 块缺少字符串字段 {key}")
    return match.group(1)


def extract_array(block: str, key: str, *, required: bool = True) -> list[str]:
    match = re.search(
        rf"^\s*{re.escape(key)}\s*=\s*\[(.*?)\]",
        block,
        flags=re.MULTILINE | re.DOTALL,
    )
    if match is None:
        if required:
            fail(f"ACL 块缺少数组字段 {key}")
        return []
    return ACL_TOKEN_PATTERN.findall(match.group(1))


def parse_inline_permissions(path: Path) -> list[InlinePermission]:
    blocks = re.split(r"^\s*\[\[permission\]\]\s*$", read_acl(path), flags=re.MULTILINE)
    permissions: list[InlinePermission] = []
    for block in blocks[1:]:
        permissions.append(
            {
                "identifier": extract_string(block, "identifier"),
                "commands": extract_array(block, "commands.allow", required=False),
            }
        )
    return permissions


default_path = PLUGIN_PERMISSIONS / "default.toml"
default_text = read_acl(default_path)
if re.search(r"^\s*\[default\]\s*$", default_text, flags=re.MULTILINE) is None:
    fail("default.toml 必须使用 Tauri 保留的 [default] 权限集")

if any(
    permission["identifier"] == "default"
    for permission in parse_inline_permissions(default_path)
):
    fail('不能用 [[permission]] identifier = "default" 代替 [default]')

permission_map: dict[str, list[str]] = {}
for path in sorted((PLUGIN_PERMISSIONS / "autogenerated/commands").glob("*.toml")):
    for permission in parse_inline_permissions(path):
        permission_map[permission["identifier"]] = permission["commands"]

default_permissions = extract_array(default_text, "permissions")
if not default_permissions:
    fail("[default].permissions 不能为空")

missing_permissions = sorted(set(default_permissions) - permission_map.keys())
if missing_permissions:
    fail(f"引用了不存在的权限: {', '.join(missing_permissions)}")

resolved_commands = {
    command
    for identifier in default_permissions
    for command in permission_map[identifier]
}
if "check_all_permissions" not in resolved_commands:
    fail("默认权限集未授权启动所需的 check_all_permissions")

leaked_default_commands = sorted(resolved_commands & SENSITIVE_COMMANDS)
if leaked_default_commands:
    fail(f"默认权限集包含敏感命令: {', '.join(leaked_default_commands)}")

allow_all = next(
    (
        permission
        for permission in parse_inline_permissions(PLUGIN_PERMISSIONS / "all.toml")
        if permission["identifier"] == "allow-all"
    ),
    None,
)
if allow_all is None:
    fail("all.toml 缺少 allow-all 权限")

allow_all_commands = set(allow_all["commands"])
leaked_all_commands = sorted(allow_all_commands & SENSITIVE_COMMANDS)
if leaked_all_commands:
    fail(f"allow-all 包含敏感命令: {', '.join(leaked_all_commands)}")

default_capability = json.loads(DEFAULT_CAPABILITY.read_text(encoding="utf-8"))
if "vcp-mobile:default" not in default_capability.get("permissions", []):
    fail("主窗口 capability 未启用 vcp-mobile:default")

notification_capability = json.loads(
    NOTIFICATION_CAPABILITY.read_text(encoding="utf-8")
)
if "vcp-mobile:allow-show-system-notification" not in notification_capability.get(
    "permissions", []
):
    fail("系统通知命令未通过独立 capability 授权")

print(
    f"vcp-mobile ACL 校验通过: 默认权限解析到 {len(resolved_commands)} 条命令，敏感命令保持隔离"
)
